/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#051424",
        "surface-dim": "#051424",
        "surface-bright": "#2c3a4c",
        "surface-container-lowest": "#010f1f",
        "surface-container-low": "#0d1c2d",
        "surface-container": "#122131",
        "surface-container-high": "#1c2b3c",
        "surface-container-highest": "#273647",
        "on-surface": "#d4e4fa",
        "on-surface-variant": "#c4c7c7",
        "inverse-surface": "#d4e4fa",
        "inverse-on-surface": "#233143",
        outline: "#8e9192",
        "outline-variant": "#444748",
        "surface-tint": "#c8c6c5",
        primary: "#c8c6c5",
        "on-primary": "#313030",
        "primary-container": "#131313",
        "on-primary-container": "#7f7d7d",
        "inverse-primary": "#5f5e5e",
        secondary: "#c6c6cb",
        "on-secondary": "#2e3035",
        "secondary-container": "#47494d",
        "on-secondary-container": "#b7b8bd",
        tertiary: "#c4c6cf",
        "on-tertiary": "#2d3037",
        "tertiary-container": "#101319",
        "on-tertiary-container": "#7b7e86",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed": "#e2e2e7",
        "secondary-fixed-dim": "#c6c6cb",
        "on-secondary-fixed": "#1a1c20",
        "on-secondary-fixed-variant": "#45474b",
        "tertiary-fixed": "#e0e2eb",
        "tertiary-fixed-dim": "#c4c6cf",
        "on-tertiary-fixed": "#191c22",
        "on-tertiary-fixed-variant": "#44474e",
        background: "#051424",
        "on-background": "#d4e4fa",
        "surface-variant": "#273647",
        // Functional severity / status accents (shared across all screens)
        critical: "#dc2626",
        high: "#ea580c",
        medium: "#eab308",
        low: "#3b82f6",
        info: "#94a3b8",
        success: "#10b981",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "24px",
        "table-cell-padding": "12px 16px",
        gutter: "16px",
        unit: "4px",
        "sidebar-width": "260px",
      },
      fontFamily: {
        "headline-md": ["Outfit", "sans-serif"],
        "label-caps": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "code-sm": ["Geist", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
