// firebase_options.dart -- PLACEHOLDER, DO NOT USE AS-IS.
//
// This file is normally auto-generated by running:
//     flutterfire configure
// after connecting this project to a Firebase project in the Firebase
// console. It reads your firebase project's platform configs and
// writes the real DefaultFirebaseOptions class here, with real API
// keys/app IDs for android/ios/web.
//
// Delete this file and run `flutterfire configure` instead of editing
// it by hand -- the values below are dummies and will fail to
// initialize Firebase if you try to run the app against them.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured -- run flutterfire configure.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not configured -- run flutterfire configure.');
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'REPLACE_ME',
  );
}
