// main.dart -- app entry point. Firebase must be initialized before
// runApp so FirebaseMessaging.onBackgroundMessage can register the
// top-level handler correctly, per FCM's own setup requirement.
//
// Requires firebase_options.dart, generated by running
// `flutterfire configure` in this project (see the setup notes handed
// off alongside this code) -- not included here since it's tied to
// your specific Firebase project.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const ProviderScope(child: VulnaraApp()));
}
