import { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";
import { StatusPill, LoadingRow, ErrorBanner } from "../components/Primitives";
import { ConfirmDialog } from "../components/ConfirmDialog";

export function RemediationReviewPage() {
  const { remediationId } = useParams();
  const navigate = useNavigate();
  const qc = useQueryClient();

  const [rejectOpen, setRejectOpen] = useState(false);
  const [rejectReason, setRejectReason] = useState("");
  const [executeOpen, setExecuteOpen] = useState(false);
  const [executeTyped, setExecuteTyped] = useState("");
  const [error, setError] = useState("");
  const [copyLabel, setCopyLabel] = useState("Copy script");

  const { data: rem, isLoading } = useQuery({
    queryKey: ["remediation", remediationId],
    queryFn: () => api.getRemediation(remediationId),
  });

  const invalidate = () => qc.invalidateQueries({ queryKey: ["remediation", remediationId] });

  const approveMutation = useMutation({
    mutationFn: () => api.approveRemediation(remediationId),
    onSuccess: invalidate,
    onError: (err) => setError(err.message),
  });

  const rejectMutation = useMutation({
    mutationFn: () => api.rejectRemediation(remediationId, rejectReason),
    onSuccess: () => {
      invalidate();
      setRejectOpen(false);
    },
    onError: (err) => setError(err.message),
  });

  const executeMutation = useMutation({
    mutationFn: () => api.markExecuted(remediationId),
    onSuccess: () => {
      invalidate();
      setExecuteOpen(false);
      setExecuteTyped("");
    },
    onError: (err) => setError(err.message),
  });

  if (isLoading || !rem) {
    return (
      <div className="page">
        <LoadingRow label="Loading remediation..." />
      </div>
    );
  }

  const copyScript = async () => {
    try {
      await navigator.clipboard.writeText(rem.technical_script);
      setCopyLabel("Copied ✓");
      setTimeout(() => setCopyLabel("Copy script"), 1500);
    } catch {
      setCopyLabel("Copy failed");
    }
  };

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }}>
            <h1 className="page-title mono" style={{ margin: 0, fontSize: 18 }}>
              {rem.remediation_id}
            </h1>
            <StatusPill status={rem.status} />
          </div>
          <p className="page-subtitle">
            For finding <span className="mono">{rem.vuln_id}</span> · target OS{" "}
            <span className="mono">{rem.target_os || "unspecified"}</span> · AI confidence{" "}
            <span className="mono">{Math.round(rem.ai_confidence * 100)}%</span>
          </p>
        </div>
        <button className="btn btn-ghost" onClick={() => navigate(-1)}>
          ← Back
        </button>
      </div>

      <ErrorBanner message={error} />

      <div className="panel" style={{ marginBottom: 16 }}>
        <div className="panel-header">
          <h3>Executive summary</h3>
          <span className="small-note">non-technical — safe to share externally after review</span>
        </div>
        <div className="panel-pad">
          <p style={{ fontSize: 13.5, lineHeight: 1.6, color: "var(--text)" }}>{rem.executive_summary}</p>
        </div>
      </div>

      <div className="panel" style={{ marginBottom: 16 }}>
        <div className="panel-header">
          <h3>Technical script</h3>
          <button className="btn btn-sm btn-ghost" onClick={copyScript}>
            {copyLabel}
          </button>
        </div>
        <div className="panel-pad">
          <div className="code-block">{rem.technical_script}</div>
        </div>
      </div>

      <div className="panel">
        <div className="panel-header">
          <h3>Review decision</h3>
        </div>
        <div className="panel-pad">
          {rem.status === "PENDING" && (
            <>
              <div className="warn-box" style={{ marginBottom: 16 }}>
                <span>⚠</span>
                <span>
                  This script was generated by AI and has not run anywhere yet. Read it fully before approving —
                  approval doesn't execute it, but it does authorize a human operator to.
                </span>
              </div>
              <div style={{ display: "flex", gap: 10 }}>
                <button className="btn btn-primary" onClick={() => approveMutation.mutate()} disabled={approveMutation.isPending}>
                  {approveMutation.isPending ? "Approving..." : "Approve"}
                </button>
                <button className="btn btn-danger" onClick={() => setRejectOpen(true)}>
                  Reject
                </button>
              </div>
            </>
          )}

          {rem.status === "APPROVED" && (
            <>
              <p style={{ fontSize: 13, color: "var(--text-dim)", marginBottom: 14 }}>
                Approved by <span className="mono">{rem.reviewed_by}</span> on{" "}
                {rem.reviewed_at ? new Date(rem.reviewed_at).toLocaleString() : "—"}. Execution happens out-of-band
                (run by your ops team or a separately authorized runner) — use the button below only once that has
                actually happened, to record it.
              </p>
              <button className="btn btn-primary" onClick={() => setExecuteOpen(true)}>
                Mark as executed
              </button>
            </>
          )}

          {rem.status === "REJECTED" && (
            <p style={{ fontSize: 13, color: "var(--text-dim)" }}>
              Rejected by <span className="mono">{rem.reviewed_by}</span> on{" "}
              {rem.reviewed_at ? new Date(rem.reviewed_at).toLocaleString() : "—"}
              {rem.reject_reason ? `: "${rem.reject_reason}"` : "."} Generate a new remediation from the finding page
              if you'd like the AI to try again.
            </p>
          )}

          {rem.status === "EXECUTED" && (
            <p style={{ fontSize: 13, color: "var(--text-dim)" }}>
              Marked executed on {rem.executed_at ? new Date(rem.executed_at).toLocaleString() : "—"}. This
              remediation's lifecycle is complete.
            </p>
          )}
        </div>
      </div>

      <ConfirmDialog
        open={rejectOpen}
        title="Reject this remediation?"
        body={
          <div className="field" style={{ marginBottom: 0 }}>
            <label>Reason (optional)</label>
            <textarea className="input" value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} placeholder="e.g. Script needs a rollback step before it's safe to run." />
          </div>
        }
        confirmLabel={rejectMutation.isPending ? "Rejecting..." : "Reject"}
        danger
        onConfirm={() => rejectMutation.mutate()}
        onCancel={() => setRejectOpen(false)}
        confirmDisabled={rejectMutation.isPending}
      />

      <ConfirmDialog
        open={executeOpen}
        title="Confirm execution record"
        body="This records that the approved script has already been run against the target by your ops team. It does not run anything itself — but the EXECUTED status is treated as ground truth elsewhere in the app, so only confirm this once it's actually true."
        requireTypedConfirm="EXECUTED"
        typedValue={executeTyped}
        onTypedChange={setExecuteTyped}
        confirmLabel={executeMutation.isPending ? "Saving..." : "Mark as executed"}
        danger
        confirmDisabled={executeTyped !== "EXECUTED" || executeMutation.isPending}
        onConfirm={() => executeMutation.mutate()}
        onCancel={() => {
          setExecuteOpen(false);
          setExecuteTyped("");
        }}
      />
    </div>
  );
}
